#!/bin/bash

#local usage function
usage(){
    echo "bn <year> <assigned gender f|F|m|M|b|B>" >&2
}

#local help function
help(){
    echo "bn - Baby Names Utility"
    echo "Version 1.0.0"
    echo "Search for rankings of baby names by year and gender."
    echo "Usage: bn <year> <assigned gender: f|F|m|M|b|B>"
    echo "--help,       display this help and exits"
    echo "Options:"
    echo "year          A four-digit year"
    echo "gender        'f/F' or 'm/M' for female or male, 'b/B' for both"
    echo "Examples: "
    echo "bn 1969 M"
    echo "Bob JEFF      Outputs the ranking for Bob in gender Male and JEFF in gender Male."
    echo "bn 1969 F"
    echo "Bob JEFF      Outputs the ranking for Bob in gender Female and JEFF in gender Female - if name does not exist, it says it doesn't exist."
}

if [[ $1 = "--help" ]]
then
    help
fi

birthYear=$1
birthGender=$2
dataFile="us_baby_names/yob${birthYear}.txt"

if [[ $# -gt 2 || $# -lt 2 ]]
then
    usage
    exit 1;
fi

if [[ $birthYear =~ ^[0-9]{4}$ ]] 
then
    true
else
    echo "Badly formatted year: $birthYear" >&2
    usage
    exit 2;
fi

if [[ $birthGender =~ ^[FfMmBb]$ ]] 
then
    true
else
    echo "Badly formatted assigned gender: $birthGender" >&2
    usage
    exit 2;
fi


if [[ -f $dataFile ]]
then
    true
else
    echo "No data for $birthYear"
    exit 4;
fi

#local rank function
rank(){
    local name=$1

    if [[ $name =~ ^[A-Za-z]+ ]]
    then
        if [[ $birthGender = "M" || $birthGender = "m" ]]
        then
            if [[ $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | grep -n -P -i -w "$name,M,[0-9]+" | grep -P -o "^[0-9]+") = "" ]]
            then
                echo "$birthYear: $name not found among the male names."
            else
                echo "$birthYear: $name ranked $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | grep -n -P -i -w "$name,M,[0-9]+" | grep -P -o "^[0-9]+") out of $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | wc -l) male names."
            fi
        elif [[ $birthGender = "F" || $birthGender = "f" ]]
        then
            if [[ $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | grep -n -P -i -w "$name,F,[0-9]+" | grep -P -o "^[0-9]+") = "" ]]
            then
                echo "$birthYear: $name not found among the female names."
            else
                echo "$birthYear: $name ranked $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | grep -n -P -i -w "$name,F,[0-9]+" | grep -P -o "^[0-9]+") out of $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | wc -l) female names."
            fi
        else
            if [[ $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | grep -n -P -i -w "$name,M,[0-9]+" | grep -P -o "^[0-9]+") = "" && $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | grep -n -P -i -w "$name,F,[0-9]+" | grep -P -o "^[0-9]+") = "" ]]
            then
                echo "$birthYear: $name not found among male names"
                echo "$birthYear: $name not found among female names"
            elif [[ $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | grep -n -P -i -w "$name,M,[0-9]+" | grep -P -o "^[0-9]+") = "" ]]
            then
                echo "$birthYear: $name not found among the male names."
                echo "$birthYear: $name ranked $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | grep -n -P -i -w "$name,F,[0-9]+" | grep -P -o "^[0-9]+") out of $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | wc -l) female names."
            elif [[ $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | grep -n -P -i -w "$name,F,[0-9]+" | grep -P -o "^[0-9]+") = "" ]]
            then
                echo "$birthYear: $name ranked $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | grep -n -P -i -w "$name,M,[0-9]+" | grep -P -o "^[0-9]+") out of $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | wc -l) male names."
                echo "$birthYear: $name not found among the female names."
            else
                echo "$birthYear: $name ranked $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | grep -n -P -i -w "$name,M,[0-9]+" | grep -P -o "^[0-9]+") out of $(cat $dataFile | grep -P -i "^[A-Z]+,M,[0-9]+" | wc -l) male names."
                echo "$birthYear: $name ranked $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | grep -n -P -i -w "$name,F,[0-9]+" | grep -P -o "^[0-9]+") out of $(cat $dataFile | grep -P -i "^[A-Z]+,F,[0-9]+" | wc -l) female names."
            fi
        fi
    else
        echo "Badly formatted name: $name"
        exit 3;
    fi
}

while read line
do
    for allNames in $line
    do
        rank $allNames
    done
done