#!/bin/bash
#
# A simple framework for testing the bn scripts
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' expected_return_value 'stdin text' 'expected stdout' 'expected stderr'
#
# Some example test cases are given. You should add more test cases.
#
# Sam Scott, McMaster University, 2024


# GLOBALS: tc = test case number, fails = number of failed cases
declare -i tc=0
declare -i fails=0

############################################
# Run a single test. Runs a given command 3 times
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = expected return value
#         $3 = standard input text to send
#         $4 = expected stdout
#         $5 = expected stderr
# RETURNS: 0 = success, 1 = bad return, 
#          2 = bad stdout, 3 = bad stderr
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local RETURN=$2
	local STDIN=$3
    local STDOUT=$4
    local STDERR=$5

    # CHECK RETURN VALUE
    $COMMAND <<< "$STDIN" >/dev/null 2>/dev/null
    local A_RETURN=$?

    if [[ "$A_RETURN" != "$RETURN" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected Return: $RETURN"
        echo "   Actual Return: $A_RETURN"
        fails=$fails+1
        return 1
    fi

    # CHECK STDOUT
    local A_STDOUT=$($COMMAND <<< "$STDIN" 2>/dev/null)

    if [[ "$STDOUT" != "$A_STDOUT" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDOUT: $STDOUT"
        echo "   Actual STDOUT: $A_STDOUT"
        fails=$fails+1
        return 2
    fi
    
    # CHECK STDERR
    local A_STDERR=$($COMMAND <<< "$STDIN" 2>&1 >/dev/null)

    if [[ "$STDERR" != "$A_STDERR" ]]; then
        echo "Test $tc Failed"
        echo "   $COMMAND"
        echo "   Expected STDERR: $STDERR"
        echo "   Actual STDERR: $A_STDERR"
        fails=$fails+1
        return 3
    fi
    
    # SUCCESS
    echo "Test $tc Passed"
    return 0
}

##########################################
# EXAMPLE TEST CASES
##########################################

# simple success
test './bn 2022 m' 0 'Sam' '2022: Sam ranked 658 out of 14255 male names.' ''

# multi line success
test './bn 2022 B' 0 'Sam' '2022: Sam ranked 658 out of 14255 male names.
2022: Sam ranked 6628 out of 17660 female names.' ''

# error case
test './bn 2022 F' 3 'Sam2' '' 'Badly formatted name: Sam2'  

# multi line error case #2
test './bn 1111 X' 2 '' '' 'Badly formatted assigned gender: X
bn <year> <assigned gender: f|F|m|M|b|B>'

# My additional test cases:

# valid input with a common name and common gender
test './bn 2020 F' 0 'Emily' '2020: Emily ranked 18 out of 17485 female names.' ''

# valid input with multiple names, space-separated
test './bn 2020 m' 0 'Chris Ross' '2020: Chris ranked 676 out of 14032 male names.
2020: Ross ranked 1323 out of 14032 male names.' ''

# # valid input with 'B' for both genders
test './bn 2020 B' 0 'Dhruv' '2020: Dhruv ranked 1059 out of 14032 male names.
2020: Dhruv not found among the female names.' ''

# invalid year format
test './bn 20XX M' 2 '' '' 'Badly formatted year: 20XX
bn <year> <assigned gender: f|F|m|M|b|B>'

# year too far - non existent file
test './bn 1800 M' 4 '' '' 'No data for 1800'

# missing gender argument
test './bn 2020' 1 '' '' 'bn <year> <assigned gender: f|F|m|M|b|B>'

# valid year and gender but a name not found in any gender
test './bn 2020 b' 0 'NonexistentName' '2020: NonexistentName not found among the male names.
2020: NonexistentName not found among the female names.' ''

# invalid name format with numbers in the end
test './bn 2020 m' 3 'Chokshi123' '' 'Badly formatted name: Chokshi123'

# invalid name format with numbers in the start
test './bn 2020 M' 3 '123Chokshi' '' 'Badly formatted name: 123Chokshi'

# case with no input names
test './bn 2020 M' 0 '' '' ''

# valid input with a common male name but in a year with no data
test './bn 2222 M' 4 'John' '' 'No data for 2222'

# valid input with multiple spaces in the front and back of name input
test './bn 2020 M' 0 '   Dhruv  Chokshi   ' '2020: Dhruv ranked 1059 out of 14032 male names.
2020: Chokshi not found among the male names.' ''

# invalid (multiple) year format
test './bn 2020 2019 M' 1 '' '' 'bn <year> <assigned gender: f|F|m|M|b|B>'


# return code
exit $fails